name: Output Secrets

on:
  workflow_dispatch:

jobs:
  output-secrets-env1:
    runs-on: ubuntu-latest
    environment: ENV1
    steps:
         
      - name: Output secrets ENV1
        run: |
          echo "Outputting secrets for ENV1"
          echo "SECRET_1 = ${{ secrets.SECRET_1 }}"
          echo "SECRET_2 = ${{ secrets.SECRET_2 }}"
          echo "SECRET_3 = ${{ secrets.SECRET_3 }}"
          echo "SECRET_4 = ${{ secrets.SECRET_4 }}"
          echo "SECRET_5 = ${{ secrets.SECRET_5 }}"
          echo "SECRET_6 = ${{ secrets.SECRET_6 }}"
          echo "SECRET_7 = ${{ secrets.SECRET_7 }}"
          echo "SECRET_8 = ${{ secrets.SECRET_8 }}"
          echo "SECRET_9 = ${{ secrets.SECRET_9 }}"
          echo "SECRET_10 = ${{ secrets.SECRET_10 }}"
          echo "SECRET_11 = ${{ secrets.SECRET_11 }}"
          echo "SECRET_12 = ${{ secrets.SECRET_12 }}"
          echo "SECRET_13 = ${{ secrets.SECRET_13 }}"
          echo "SECRET_14 = ${{ secrets.SECRET_14 }}"
          echo "SECRET_15 = ${{ secrets.SECRET_15 }}"
          echo "SECRET_16 = ${{ secrets.SECRET_16 }}"
          echo "SECRET_17 = ${{ secrets.SECRET_17 }}"
          echo "SECRET_18 = ${{ secrets.SECRET_18 }}"
          echo "SECRET_19 = ${{ secrets.SECRET_19 }}"
          echo "SECRET_20 = ${{ secrets.SECRET_20 }}"
          echo "SECRET_21 = ${{ secrets.SECRET_21 }}"
          echo "SECRET_22 = ${{ secrets.SECRET_22 }}"
          echo "SECRET_23 = ${{ secrets.SECRET_23 }}"
          echo "SECRET_24 = ${{ secrets.SECRET_24 }}"
          echo "SECRET_25 = ${{ secrets.SECRET_25 }}"
          echo "SECRET_26 = ${{ secrets.SECRET_26 }}"
          echo "SECRET_27 = ${{ secrets.SECRET_27 }}"
          echo "SECRET_28 = ${{ secrets.SECRET_28 }}"
          echo "SECRET_29 = ${{ secrets.SECRET_29 }}"
          echo "SECRET_30 = ${{ secrets.SECRET_30 }}"
          echo "SECRET_31 = ${{ secrets.SECRET_31 }}"
          echo "SECRET_32 = ${{ secrets.SECRET_32 }}"
          echo "SECRET_33 = ${{ secrets.SECRET_33 }}"
          echo "SECRET_34 = ${{ secrets.SECRET_34 }}"
          echo "SECRET_35 = ${{ secrets.SECRET_35 }}"
          echo "SECRET_36 = ${{ secrets.SECRET_36 }}"
          echo "SECRET_37 = ${{ secrets.SECRET_37 }}"
          echo "SECRET_38 = ${{ secrets.SECRET_38 }}"
          echo "SECRET_39 = ${{ secrets.SECRET_39 }}"
          echo "SECRET_40 = ${{ secrets.SECRET_40 }}"
          echo "SECRET_41 = ${{ secrets.SECRET_41 }}"
          echo "SECRET_42 = ${{ secrets.SECRET_42 }}"
          echo "SECRET_43 = ${{ secrets.SECRET_43 }}"
          echo "SECRET_44 = ${{ secrets.SECRET_44 }}"
          echo "SECRET_45 = ${{ secrets.SECRET_45 }}"
          echo "SECRET_46 = ${{ secrets.SECRET_46 }}"
          echo "SECRET_47 = ${{ secrets.SECRET_47 }}"
          echo "SECRET_48 = ${{ secrets.SECRET_48 }}"
          echo "SECRET_49 = ${{ secrets.SECRET_49 }}"
          echo "SECRET_50 = ${{ secrets.SECRET_50 }}"
          echo "SECRET_51 = ${{ secrets.SECRET_51 }}"
          echo "SECRET_52 = ${{ secrets.SECRET_52 }}"
          echo "SECRET_53 = ${{ secrets.SECRET_53 }}"
          echo "SECRET_54 = ${{ secrets.SECRET_54 }}"
          echo "SECRET_55 = ${{ secrets.SECRET_55 }}"
          echo "SECRET_56 = ${{ secrets.SECRET_56 }}"
          echo "SECRET_57 = ${{ secrets.SECRET_57 }}"
          echo "SECRET_58 = ${{ secrets.SECRET_58 }}"
          echo "SECRET_59 = ${{ secrets.SECRET_59 }}"
          echo "SECRET_60 = ${{ secrets.SECRET_60 }}"
          echo "SECRET_61 = ${{ secrets.SECRET_61 }}"
          echo "SECRET_62 = ${{ secrets.SECRET_62 }}"
          echo "SECRET_63 = ${{ secrets.SECRET_63 }}"
          echo "SECRET_64 = ${{ secrets.SECRET_64 }}"
          echo "SECRET_65 = ${{ secrets.SECRET_65 }}"
          echo "SECRET_66 = ${{ secrets.SECRET_66 }}"
          echo "SECRET_67 = ${{ secrets.SECRET_67 }}"
          echo "SECRET_68 = ${{ secrets.SECRET_68 }}"
          echo "SECRET_69 = ${{ secrets.SECRET_69 }}"
          echo "SECRET_70 = ${{ secrets.SECRET_70 }}"
          echo "SECRET_71 = ${{ secrets.SECRET_71 }}"
          echo "SECRET_72 = ${{ secrets.SECRET_72 }}"
          echo "SECRET_73 = ${{ secrets.SECRET_73 }}"
          echo "SECRET_74 = ${{ secrets.SECRET_74 }}"
          echo "SECRET_75 = ${{ secrets.SECRET_75 }}"
          echo "SECRET_76 = ${{ secrets.SECRET_76 }}"
          echo "SECRET_77 = ${{ secrets.SECRET_77 }}"
          echo "SECRET_78 = ${{ secrets.SECRET_78 }}"
          echo "SECRET_79 = ${{ secrets.SECRET_79 }}"
          echo "SECRET_80 = ${{ secrets.SECRET_80 }}"
          echo "SECRET_81 = ${{ secrets.SECRET_81 }}"
          echo "SECRET_82 = ${{ secrets.SECRET_82 }}"
          echo "SECRET_83 = ${{ secrets.SECRET_83 }}"
          echo "SECRET_84 = ${{ secrets.SECRET_84 }}"
          echo "SECRET_85 = ${{ secrets.SECRET_85 }}"
          echo "SECRET_86 = ${{ secrets.SECRET_86 }}"
          echo "SECRET_87 = ${{ secrets.SECRET_87 }}"
          echo "SECRET_88 = ${{ secrets.SECRET_88 }}"
          echo "SECRET_89 = ${{ secrets.SECRET_89 }}"
          echo "SECRET_90 = ${{ secrets.SECRET_90 }}"
          echo "SECRET_91 = ${{ secrets.SECRET_91 }}"
          echo "SECRET_92 = ${{ secrets.SECRET_92 }}"
          echo "SECRET_93 = ${{ secrets.SECRET_93 }}"
          echo "SECRET_94 = ${{ secrets.SECRET_94 }}"
          echo "SECRET_95 = ${{ secrets.SECRET_95 }}"
          echo "SECRET_96 = ${{ secrets.SECRET_96 }}"
          echo "SECRET_97 = ${{ secrets.SECRET_97 }}"
          echo "SECRET_98 = ${{ secrets.SECRET_98 }}"
          echo "SECRET_99 = ${{ secrets.SECRET_99 }}"
          echo "SECRET_100 = ${{ secrets.SECRET_100 }}"



  output-secrets-env2:
    runs-on: ubuntu-latest
    environment: ENV2
    steps:

      
      - name: Output secrets ENV2
        run: |
          echo "Outputting secrets for ENV1"
          echo "SECRET_1 = ${{ secrets.SECRET_1 }}"
          echo "SECRET_2 = ${{ secrets.SECRET_2 }}"
          echo "SECRET_3 = ${{ secrets.SECRET_3 }}"
          echo "SECRET_4 = ${{ secrets.SECRET_4 }}"
          echo "SECRET_5 = ${{ secrets.SECRET_5 }}"
          echo "SECRET_6 = ${{ secrets.SECRET_6 }}"
          echo "SECRET_7 = ${{ secrets.SECRET_7 }}"
          echo "SECRET_8 = ${{ secrets.SECRET_8 }}"
          echo "SECRET_9 = ${{ secrets.SECRET_9 }}"
          echo "SECRET_10 = ${{ secrets.SECRET_10 }}"
          echo "SECRET_11 = ${{ secrets.SECRET_11 }}"
          echo "SECRET_12 = ${{ secrets.SECRET_12 }}"
          echo "SECRET_13 = ${{ secrets.SECRET_13 }}"
          echo "SECRET_14 = ${{ secrets.SECRET_14 }}"
          echo "SECRET_15 = ${{ secrets.SECRET_15 }}"
          echo "SECRET_16 = ${{ secrets.SECRET_16 }}"
          echo "SECRET_17 = ${{ secrets.SECRET_17 }}"
          echo "SECRET_18 = ${{ secrets.SECRET_18 }}"
          echo "SECRET_19 = ${{ secrets.SECRET_19 }}"
          echo "SECRET_20 = ${{ secrets.SECRET_20 }}"
          echo "SECRET_21 = ${{ secrets.SECRET_21 }}"
          echo "SECRET_22 = ${{ secrets.SECRET_22 }}"
          echo "SECRET_23 = ${{ secrets.SECRET_23 }}"
          echo "SECRET_24 = ${{ secrets.SECRET_24 }}"
          echo "SECRET_25 = ${{ secrets.SECRET_25 }}"
          echo "SECRET_26 = ${{ secrets.SECRET_26 }}"
          echo "SECRET_27 = ${{ secrets.SECRET_27 }}"
          echo "SECRET_28 = ${{ secrets.SECRET_28 }}"
          echo "SECRET_29 = ${{ secrets.SECRET_29 }}"
          echo "SECRET_30 = ${{ secrets.SECRET_30 }}"
          echo "SECRET_31 = ${{ secrets.SECRET_31 }}"
          echo "SECRET_32 = ${{ secrets.SECRET_32 }}"
          echo "SECRET_33 = ${{ secrets.SECRET_33 }}"
          echo "SECRET_34 = ${{ secrets.SECRET_34 }}"
          echo "SECRET_35 = ${{ secrets.SECRET_35 }}"
          echo "SECRET_36 = ${{ secrets.SECRET_36 }}"
          echo "SECRET_37 = ${{ secrets.SECRET_37 }}"
          echo "SECRET_38 = ${{ secrets.SECRET_38 }}"
          echo "SECRET_39 = ${{ secrets.SECRET_39 }}"
          echo "SECRET_40 = ${{ secrets.SECRET_40 }}"
          echo "SECRET_41 = ${{ secrets.SECRET_41 }}"
          echo "SECRET_42 = ${{ secrets.SECRET_42 }}"
          echo "SECRET_43 = ${{ secrets.SECRET_43 }}"
          echo "SECRET_44 = ${{ secrets.SECRET_44 }}"
          echo "SECRET_45 = ${{ secrets.SECRET_45 }}"
          echo "SECRET_46 = ${{ secrets.SECRET_46 }}"
          echo "SECRET_47 = ${{ secrets.SECRET_47 }}"
          echo "SECRET_48 = ${{ secrets.SECRET_48 }}"
          echo "SECRET_49 = ${{ secrets.SECRET_49 }}"
          echo "SECRET_50 = ${{ secrets.SECRET_50 }}"
          echo "SECRET_51 = ${{ secrets.SECRET_51 }}"
          echo "SECRET_52 = ${{ secrets.SECRET_52 }}"
          echo "SECRET_53 = ${{ secrets.SECRET_53 }}"
          echo "SECRET_54 = ${{ secrets.SECRET_54 }}"
          echo "SECRET_55 = ${{ secrets.SECRET_55 }}"
          echo "SECRET_56 = ${{ secrets.SECRET_56 }}"
          echo "SECRET_57 = ${{ secrets.SECRET_57 }}"
          echo "SECRET_58 = ${{ secrets.SECRET_58 }}"
          echo "SECRET_59 = ${{ secrets.SECRET_59 }}"
          echo "SECRET_60 = ${{ secrets.SECRET_60 }}"
          echo "SECRET_61 = ${{ secrets.SECRET_61 }}"
          echo "SECRET_62 = ${{ secrets.SECRET_62 }}"
          echo "SECRET_63 = ${{ secrets.SECRET_63 }}"
          echo "SECRET_64 = ${{ secrets.SECRET_64 }}"
          echo "SECRET_65 = ${{ secrets.SECRET_65 }}"
          echo "SECRET_66 = ${{ secrets.SECRET_66 }}"
          echo "SECRET_67 = ${{ secrets.SECRET_67 }}"
          echo "SECRET_68 = ${{ secrets.SECRET_68 }}"
          echo "SECRET_69 = ${{ secrets.SECRET_69 }}"
          echo "SECRET_70 = ${{ secrets.SECRET_70 }}"
          echo "SECRET_71 = ${{ secrets.SECRET_71 }}"
          echo "SECRET_72 = ${{ secrets.SECRET_72 }}"
          echo "SECRET_73 = ${{ secrets.SECRET_73 }}"
          echo "SECRET_74 = ${{ secrets.SECRET_74 }}"
          echo "SECRET_75 = ${{ secrets.SECRET_75 }}"
          echo "SECRET_76 = ${{ secrets.SECRET_76 }}"
          echo "SECRET_77 = ${{ secrets.SECRET_77 }}"
          echo "SECRET_78 = ${{ secrets.SECRET_78 }}"
          echo "SECRET_79 = ${{ secrets.SECRET_79 }}"
          echo "SECRET_80 = ${{ secrets.SECRET_80 }}"
          echo "SECRET_81 = ${{ secrets.SECRET_81 }}"
          echo "SECRET_82 = ${{ secrets.SECRET_82 }}"
          echo "SECRET_83 = ${{ secrets.SECRET_83 }}"
          echo "SECRET_84 = ${{ secrets.SECRET_84 }}"
          echo "SECRET_85 = ${{ secrets.SECRET_85 }}"
          echo "SECRET_86 = ${{ secrets.SECRET_86 }}"
          echo "SECRET_87 = ${{ secrets.SECRET_87 }}"
          echo "SECRET_88 = ${{ secrets.SECRET_88 }}"
          echo "SECRET_89 = ${{ secrets.SECRET_89 }}"
          echo "SECRET_90 = ${{ secrets.SECRET_90 }}"
          echo "SECRET_91 = ${{ secrets.SECRET_91 }}"
          echo "SECRET_92 = ${{ secrets.SECRET_92 }}"
          echo "SECRET_93 = ${{ secrets.SECRET_93 }}"
          echo "SECRET_94 = ${{ secrets.SECRET_94 }}"
          echo "SECRET_95 = ${{ secrets.SECRET_95 }}"
          echo "SECRET_96 = ${{ secrets.SECRET_96 }}"
          echo "SECRET_97 = ${{ secrets.SECRET_97 }}"
          echo "SECRET_98 = ${{ secrets.SECRET_98 }}"
          echo "SECRET_99 = ${{ secrets.SECRET_99 }}"
          echo "SECRET_100 = ${{ secrets.SECRET_100 }}"
